# District Heating: An Investigation into the Efficiency of a Centralized Heating System
#### Thermodynamics, Final Project  |  Karen Hinh, Mads Young
District heating is a method of home climate control that should be more utilized in the future due to its energy efficiency and friendliness to more sustainable energy sources. For heat sources, there’s geothermal or water source heat pumps, as well as gas or electric boilers, but for the purposes of this project, we are going to focus on exploring the differences between water source heat pumps and gas / electric boilers.

In this project, we will investigate the efficiencies of a small scale district heating network with different heat sources (water source heat pumps and gas / electric boilers) and mediums of heat transfer (liquid water vs steam). If there’s extra time, we would be interested in exploring the efficiency difference between small scale district heating with decentralized heating in houses. 

To accomplish this, we will build a thermodynamic model of a small scale district heating network with variables such as the amount of heat put in, the initial and final (after heat extraction) temperature of the fluid and pressure differences within the heat pump. We will use the model to compare energy cost, thermodynamic properties, and efficiency of the relevant heating methods to ideally prove the superiority of district heating networks over decentralized heating. This will be done in coolprop.

In [27]:
import CoolProp.CoolProp as CP
import CoolProp.Plots as CPP
import numpy as np
import matplotlib.pyplot as plt

# Simplified Model

Simple Diagram          |  System Diagram          | TS Diagram
:----------------------:|:------------------------:|:--------------------------:
![](simple_diagram.png) |  ![](system_diagram.png) | ![](ts_diagram.jpeg)

- Q56 represents the heat transfer _into_ the evaporator.
- Q23 represents the heat transfer _out of_ the condensor.
- W12 represents the work _into_ the compressor.

## Defining State Variables

In [85]:
m = 20 # kg, of water
c = 122.5 # J/kg-C, of r11
deltaT = np.array([1,10]) / 3600 # C/s, "Qout" from the house ranges from 1C-10C / hour

T1 = 40 + 273.15 # K
T2 = 25 + 273.15 # K
T3 = 45 + 273.15 # K
T4 = 40 + 273.15 # K
##T5 = T1
##T6 = T1

In [86]:
substance = 'R11'

# Enthalpy calculations
h1 = CP.PropsSI('H', 'T',T1, 'Q',1, substance) / 1000 # vapor --> 2538.1 kJ/kg
h2 = CP.PropsSI('H', 'T',T2, 'Q',1, substance) / 1000 # vapor --> 2660.1 kJ/kg
h3 = CP.PropsSI('H', 'T',T3, 'Q',0, substance) / 1000 # liquid --> 251.13 kJ/kg
h4 = CP.PropsSI('H', 'T',T4, 'Q',0, substance) / 1000 # liquid --> 209.33 kJ/kg
##h5 = 2452.1 # kJ/kg, liquid-vapor from textbook
##h6 = CP.PropsSI('H', 'T',T6, 'Q',1, substance) / 1000 # vapor --> 2538.1 kJ/kg

print(h1, h2, h3, h4,) ##h5, h6

410.29454596754215 402.6446586498881 239.61664930737723 235.11103820513713


## Q56: Heat Transfer into the Evaporator (Qc)

In [87]:
Q41 = m*c*deltaT / 1000 # kW

Q41

array([0.00068056, 0.00680556])

In [88]:
m_flowrate = Q41 / (h1 - h4) # kg/s

m_flowrate

array([3.88481521e-06, 3.88481521e-05])

## Q23: Heat Transfer out of the Condensor (Qh)

In [89]:
Q23 = m_flowrate * (h2 - h3) # kW

Q23

array([0.00063333, 0.00633334])

## W12: Work into Compressor (Win)

In [90]:
W12 = m_flowrate * (h1 - h2) # kW

W12

array([2.97183986e-05, 2.97183986e-04])

## COP

In [91]:
COP = Q23 / W12 # Qh/Win

print('The COP of this heat pump cycle is: ' + str(COP[0]))

The COP of this heat pump cycle is: 21.311164801902624
